spring.datasource.url=jdbc:mysql://localhost:3306/authify
spring.datasource.username=root
spring.datasource.password=super
spring.jpa.hibernate.ddl-auto=update
jwt.secret.key=thisisthelongestjwttokenkey
server.servlet.context-path=/api/v1.0
